name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: say hi
        run: echo "hello from CI"

      - name: say bye
        run: echo "goodbye"
