name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: say hi
        run: echo "hello from CI"

      - name: say bye
        run: echo "goodbye"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout and clone repo
        uses: actions/checkout@v2

      - name: install dependencies
        run: npm i

      - name: test the app
        run: npm run test-app
