name: Test and Deploy

on:
  push:
    branches:
      - main

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: say hi
        run: echo "hello from CI"

      - name: say bye
        run: echo "goodbye"

  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout and clone repo
        uses: actions/checkout@v2

      - name: setup postgres
        uses: harmon758/postgresql-action@v1
        with:
          postgresql db: boardgame-reviews
          postgresql user: boardgame-user
          postgresql password: boardgame-password

      - name: install dependencies
        run: npm i

      - name: test the app
        run: PGDATABASE=boardgame-reviews PGUSER=boardgame-user PGPASSWORD=boardgame-password npm run test-app
